name: Deploy EKS Cluster

on:
  push:
    branches:
      - main

jobs:
  plan:
    runs-on: ubuntu-latest
    outputs:
      plan-exists: ${{ steps.check-plan.outputs.plan-exists }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Cache Terraform Modules
      uses: actions/cache@v2
      with:
        path: |
          ~/.terraform.d/plugin-cache
          .terraform
        key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.tf') }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.7

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
  
    - name: Terraform Init
      run: terraform init
    
    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      id: plan
      run: |
        set +e 
        terraform plan -out=tfplan
        PLAN_EXIT_CODE=$?
        if [ $PLAN_EXIT_CODE -eq 2 ]; then
          echo "Changes detected that need to be applied."
          echo "::set-output name=plan-exists::true"
        elif [ $PLAN_EXIT_CODE -eq 0 ]; then
          echo "No changes detected."
          echo "::set-output name=plan-exists::false"
        else
          echo "Error during plan."
          exit 1  # Exit with error if Terraform plan fails
        fi
        set -e 
    
    - name: Upload Terraform Plan
      uses: actions/upload-artifact@v2
      with:
          name: terraform-plan
          path: tfplan
       
  apply:
    runs-on: ubuntu-latest
    needs: plan
    if: needs.plan.outputs.plan-exists == 'true'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Download Terraform Plan
      uses: actions/download-artifact@v2
      with:
        name: terraform-plan
        path: .
    
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
          terraform_version: 1.5.7
    
    - name: Terraform Init
      run: terraform init -reconfigure

    - name: Terraform Apply
      run: terraform apply -auto-approve

